### ISSUE TITLE
Blank Search times out.

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/TLCMap-support#10]
If do not select any search filters and leave the search field blank it times out. I think this is because it is trying to return everything which is too much. However, it shouldn't time out because it has been set to '200 places' (or other limit), so should be only retrieving 200 results.
This also impacts on other search filters when the text box is left blank. Eg: If I do not enter  word in the search field, but select 'Layer Type' = Placename it times out. Instead it should be returning 200 placenames.

**Comment by IanMcCrabb** [comment]
@MufengNiu could prirotise this one please as we don't want timeouts during testing.  Lets make it work with the number of places being returned as Bill suggests

**Comment by IanMcCrabb** [comment]
OK
