### ISSUE TITLE
Add Place help tips

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/TLCMap-support#13]
In the pop up for Add Place:

- Add a help tip to 'Title' that says, 'A short title for the information you are adding about this place.'

- Change the help information for 'Feature Term' to be, "A list of feature terms for types of places such as mountains, towns or rivers, used by government bodies. Start typing to see a list of terms." and remove the link.

- Add a help tip for Date Start that says, "Type a year, date, or select from calendar."

- Change the help tip for LGA to be 'Local Government Area'.

- Change the help tip for 'Linkback URL' to "This is the main link for more information on another website about this place. Eg: a newspaper article, record in a museum database, video of a story, organisations website, etc. It must start with http:// or https://"

- Add help tip for 'Source (Website url, ISBN, Book title, etc)' that says, "Please add the citation or source of this information, to ensure it is reliable and so others can follow the references."

- Change 'Extended Data' help tip to ('For advanced use, you can add any kind of data to places as key-value pairs. When importing and exporting this data is in columns under headings.')

- When you click the help for Latitude it says 'Try Quick Coordinates' and links to Quick Coordinates. If I click that it loads in the same page, and I'm lost. Change the text to 'Use decimal coordinates. For adding many places, try Quick Coordinates and upload a CSV.' and make it open Quick Coordinates in a new tab.

**Comment by IanMcCrabb** [comment]
OK
