### ISSUE TITLE
Add place layer options

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/TLCMap-support#14]
Under the heading for 'Add a place to TLCMap' it says "First. choose a layer. Every place in TLCMap belongs to a layer. You can add more places to this layer later."
Change it to, "Places in TLCMap are part of a map layer. Choose a layer or create a new layer to add this place to it. You can edit the layer details later."

Replace the current layer drop down and button with:

- A text box with a button saying 'New Layer'.
- A drop down list with all the user's layers. If the user has no layers, it is automatically populated with a "<user>'s Layer".
- If the user types in the box and clicks the 'New layer' button, it adds this layer name to the list of layers in the drop down and it is selected.
- When user clicks 'Save', if the selected layer doesn't already exist, create it. Add the place to selected layer.
(Normally Description field is required for a layer. Remove this requirement, so a new layer only requires a title.)

Alternatively, if this is too much effort, we could do this which requires less change but isn't as good:
- The button says 'Edit layer' but it doesn't edit a layer, it goes to the Add Layer Screen. Make the button say 'New layer'. It should open in a new tab.

**Comment by IanMcCrabb** [comment]
Lets do the 2nd option straight away.

**Comment by IanMcCrabb** [comment]
@MufengNiu I think we just need to make the button say New Layer not Edit Layer 

![image](https://github.com/user-attachments/assets/a38c263b-eb95-4b39-8481-1bdb6b653296)

**Comment by IanMcCrabb** [comment]
OK
