### ISSUE TITLE
Up and down arrows

### ISSUE THREAD

**Issue by HughCraig** [HughCraig/TLCMap-support#17]
This is from Mitchell Harrop:
"Downward pointing arrow to the left of the search expands the search. Same arrow collapses the dialogue that pops up when you click on a space. Same symbol does the opposite thing!"
--It looks as though that there is a difference between clicking on a space when it is at the top of the screen, in which case downward arrow means open downwards, and clicking on a space at the bottom of the screen, when up arrow means expand upwards. 
If this is the case, maybe the current system is OK.

**Comment by BillPascoe** [comment]
Make the search box arrow point the same way as the pop up arrow.

**Comment by BillPascoe** [comment]
Duplicate of https://github.com/HughCraig/TLCMap-support/issues/32
