### ISSUE TITLE
Layer name in place pop-up boxes

### ISSUE THREAD

**Issue by HughCraig** [HughCraig/TLCMap-support#18]
This is from Bill Palmer:
"We talked about this, but the pop up boxes should say what layer the point is from."
--Currently the list view shows the layer the point is from, but the pop-ups in the map view do not. It would be good it the map layer could appear in the pop-ups for points.

**Comment by BillPascoe** [comment]
This issue is also described in GHAP issue tracker: https://github.com/HughCraig/GHAP/issues/406
We need the title of the layer, not just 'TLCMap Layer' hyperlinked.

**Comment by IanMcCrabb** [comment]
Ok
