### ISSUE TITLE
Label for spinning icon

### ISSUE THREAD

**Issue by HughCraig** [HughCraig/TLCMap-support#19]
This is from Mitchell Harrop:
"The “loading...” spinning doughnut… could say what it is loading. “Loading (more) random places….”

**Comment by BillPascoe** [comment]
If it's easy, say 'Loading random places...'

**Comment by IanMcCrabb** [comment]
@MufengNiu figure we need to distinguish the message.  If it loading random places then that's fine.   

Can we change the message whenever there is value in the search box or settings in advanced search to just say loading places... instead of loading random places...

**Comment by IanMcCrabb** [comment]
OK
