### ISSUE TITLE
Map, Cluster, List titles

### ISSUE THREAD

**Issue by HughCraig** [HughCraig/TLCMap-support#20]
This is from Mitchell Harrop:
"Map, Cluster or List…
Cluster is also a Map. Change “Map” to something else? “Points”?"

**Comment by IanMcCrabb** [comment]
I think its OK.

**Comment by BillPascoe** [comment]
Change 'map' to 'points'.
We are already looking at a map, so you don't have to select 'map' to get a map. It think we did this to differentiate from 'list' but once you have clicked 'list' it would be clear you have to click 'points' to get back to the map.
