### ISSUE TITLE
Text on front page

### ISSUE THREAD

**Issue by HughCraig** [HughCraig/TLCMap-support#21]
This is from Penny Edmonds:
"Hello all, I suggest that this is on the very front landing page as it is still not completely clear what TLC map is about. We have:

'TLCMap is a set of tools that work together for mapping Australian history and culture'. 

How about more from the current website ('Getting Started'):

'We are developing systems for humanities researchers and community to build maps for different purposes, which can be shared, combined, searched and visualised in different ways, from finding places in texts, to representing Indigenous knowledge, to statistical analysis of spatiotemporal data, to journey animations'.

?"

**Comment by BillPascoe** [comment]
Proposed new page is more succinct and better "Mapping Australian history and culture". Longer sentences can go on the 'about' page.
