### ISSUE TITLE
Layers

### ISSUE THREAD

**Issue by HughCraig** [HughCraig/TLCMap-support#22]
This is from Nicole Davis:
"Map layers not obvious at right. I only knew to go look because I know there should be layers somewhere. When you hover over it just says expand, not expand what. I think layers are a key part of the map and should be more obvious."

**Comment by BillPascoe** [comment]
Not clear where else they could be that's better.

**Comment by IanMcCrabb** [comment]
If the concern is My Layers and My Multilayers they can be expose on the LHS in the green stripe next to Layers and Multilayers

**Comment by BillPascoe** [comment]
Change the menu at the right for logged in users to have two sections as follows:

My Maps

- My Layers
- My Multilayers
- My Texts
- My Searches

Username (eg: Bill Pascoe)

- Profile
- Admin (if user is an admin)
- Log Out
