### ISSUE TITLE
Search Box 

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/TLCMap-support#25]
The placeholder text in the search box on the left hand side currently states “Enter search”. This can be more descriptive to help explain what is being searched. Users wanted to understand what the site is actually about and this is a simple way to give them more context. Suggestions:

●	“Search places…”
●	“Search place names and more…”
●	“Search historical places and more…”

The search button has the search magnifying icon as well as the text “Search”. The placeholder also has the word “search” in it, so this feels redundant. Could get rid of the word search from the search button to free up some space (spoiler alert: some of the suggested changes may need more space on this row!).

**Comment by BillPascoe** [comment]
Make it say “Search places and culture”. Drop lable 'search' from the search button and use magnifying glass icon only.

**Comment by IanMcCrabb** [comment]
OK
