### ISSUE TITLE
Contians Button

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/TLCMap-support#26]
The options to the right of the “Enter search” box could also change to give users more of a sense of what the site is all about. Also note change of order helps users understand what each option does:

●	Contains Text (previously “Contains”)
●	Exact Text Match (previously “Exact Match”)
●	Similar Text Match (previously “Fuzzy”)
●	ANPS ID Lookup (previously “anps_id”)
○	(This is giving subtle context that the website can be used as a “lookup” - a database of useful information)

Could do this without the word “Text” in each. Depends on available space.

**Comment by BillPascoe** [comment]
Use:
● Contains
● Exact Match
● Similar Match
● Place ID

**Comment by IanMcCrabb** [comment]
OK
