### ISSUE TITLE
Reset Button

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/TLCMap-support#27]
The “Reset” button only really makes sense in context of the advanced search. If doing a simple search there is only the search box, “Contains” selector and checkboxes to reset. These are respectively:

●	blank, 
●	the first option and, 
●	all ticked.

As such, there is not that much cognitive effort for a user to reset those as the defaults are intuitive and quick to change. The reset button probably belongs under the advanced search. In this space it has room to be “Reset all search and reload map” or similar and frees space in the top row. Also when drawing polygons this is when you most want to look for a reset button!

**Comment by BillPascoe** [comment]
No leave it next to search. If you've been messing with everything, this is the most central point to look for and find the reset button. No big problem that the basic search options are simple. This simplicity helps user know where the reset button is when they need it later. Also it is a general button for the whole search, not a subcategory of search and filter, so it should remain in the 'general' area.
