### ISSUE TITLE
Layers, NCG and ANPS Buttons

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/TLCMap-support#28]
Users found the colour scheme of these a bit too close together to distinguish. 

There was feedback that the Layers checkbox should be the third option. I can’t remember the reasoning behind this, but I do remember thinking that it was very good reasoning at the time and I wrote it down. Sorry. 

The Layers checkbox background colour should be the same colour as the plus button in the bottom right hand corner of the map (i.e. the add new layer button). This is because contributing researchers will typically be adding new Layers rather than a direct contribution to ANPS the first time they try to use the site and sign up. Experienced users will be going via their own layers and multilayers interface so this doesn’t really matter for them.  

Layers, ANPS and NCG checkbox labels are tricky but very important to provide users subtle context as to what the website is all about. Suggested change:

●	ANPS Data (?)
○	Mousing over the “(?)” shows a tooltip “Official Australian Placenames …” rather than the current mouseover on the text. Works in the same way/consistent with the question mark icon next to “Specify map area” in the advanced search. 

![image](https://github.com/user-attachments/assets/07373bdf-8339-4514-8828-20cf5b3fc277)
 
●	NCG Data (?)
○	Clicking on the “(?)” shows a tooltip.
●	TLCMap Layers

Adding the word “data” makes it apparent that two of the options are more official (imho). Calling it “TLCMap Layers” lets the user know this site has data that is separate yet of equal status. Making “Layers” last means users will interpret the word “Layer” as being a layer of data - because the two they read before it were about data, so this third one must be as well!  It also implies that layers are data layered on top of something else, adding additional meaning beyond just a dataset or two.

**Comment by BillPascoe** [comment]
'Layers' button could move or remain, but it should have a tooltip that says 'Layers of culture and history.'
Consider all points same colour but different shape (this is also good for colourblind).
Yes layers button same colour as add place button.
Disagree a bit on the labelling. If the two preceding are 'data' and the last is 'layer' user will assume a layer is not data. In any case we should avoid the term 'data' in favour of 'layer'. The distinction is between 2 official gazetteers of placenames, and one set of many layers about culture and history contributed by many people. Suggest we use 'Gazetteers' and 'Layers' as the basis for relabeling. Eg: ANPS Gazeetteer, NCG Gazetteer, Layers.

**Comment by IanMcCrabb** [comment]
'Layers' button could move or remain, but it should have a tooltip that says 'Layers of culture and history.'
-switch positions of NCG and Layers buttons

Consider all points same colour but different shape (this is also good for colourblind).
-lets not change at the moment.  The semantics of different shapes might be more problematic 

Yes layers button same colour as add place button.
-Change add place button to match Layers colour

Disagree a bit on the labelling. If the two preceding are 'data' and the last is 'layer' user will assume a layer is not data. In any case we should avoid the term 'data' in favour of 'layer'. The distinction is between 2 official gazetteers of placenames, and one set of many layers about culture and history contributed by many people. Suggest we use 'Gazetteers' and 'Layers' as the basis for relabeling. Eg: ANPS Gazeetteer, NCG Gazetteer, Layers.
-this will make the buttons too long and they already have tool tips.  Lets just add 'Contributed layers' as a tooltip on Layers button.

**Comment by IanMcCrabb** [comment]
OK

**Comment by IanMcCrabb** [comment]
@MufengNiu can you change the word to Gazetteer in the ANPS button.

**Comment by IanMcCrabb** [comment]
OK
