### ISSUE TITLE
Map, Cluster, List

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/TLCMap-support#29]
The “Cluster” option is also a map. So we can change the “Map” option to provide more context on what is being shown and what the site is all about. Ideas:

●	“Map” → “Individual Places”
●	“Map” → “Placenames”
●	“Map” → “Place names and more…”
●	“Map” → “Places and more…”
●	“Map” → “Historical places and more…”

**Comment by BillPascoe** [comment]
No leave it as Map, Cluster, List. It's most succinct. So a person figures out a cluster is another way of viewing the map, that's ok. We don't have enough nuance in the data to break it down as suggested and it would be noisy.
