### ISSUE TITLE
Multiple movements load multiple time

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/TLCMap-support#3]
It's good that the map loading has a timer so that you understand there is a short delay and then things load. There is still a problem where if I make multiple movements within the time limit, when the timer stops it has run a query for every movement and then loads them all one after another. If I move left then down, then it loads dots twice after the timer stops. If I move and zoom and move again it loads dots three times after the timer stops. It should only load the last one.

**Comment by BillPascoe** [comment]
Just some more detail about the behaviour. It's not as bad as I thought. Eg: If I am zoomed in to Sydney, and then I want to zoom into Melbourne there is a lot of zoom in and out and a lot of moving of the map, perhaps 10 mouse events, but it only loads dots 2 or 3 times, not 15. That is ok and is expected by user. It only seemed wierd when I made two small movements that it load both of them. So it would still be good to only load once, but it is not as if I will crash the map or become very confused if I am doing a large amount of rapid movements.

**Comment by IanMcCrabb** [comment]
We can perhaps increase the time just little more after the user stops moving before we load a new set of points

**Comment by BillPascoe** [comment]
I think this works reasonably well now.
