### ISSUE TITLE
Place Numbers

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/TLCMap-support#30]
The “100/200/etc places” drop down selection could go into the advanced search section to save space. When you are first looking around to work out what the site is all about, you don’t really care about how many places come back. I think “looking around to work out what the site is” is the primary purpose of the top row search for new users. (The secondary purpose is a quick search for experienced users - hence the search by ANPS ID as an option)

**Comment by BillPascoe** [comment]
Agreed.
