### ISSUE TITLE
Hamburger Menu

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/TLCMap-support#31]
Menu Hamburger - I think this belongs to the right of the “Log in” button. Half of the users didn’t find this where it currently sits (gave users a task to find out more about the project).

**Comment by BillPascoe** [comment]
Agreed.

**Comment by IanMcCrabb** [comment]
@MufengNiu seemed to have missed this one.  Can we put the hamburger menu that us currently in the header as 3 white stipes at the very right of the green stripe.

![image](https://github.com/user-attachments/assets/9c32c3ff-dce9-4c63-8129-9fc38c33727a)

**Comment by IanMcCrabb** [comment]
OK
