### ISSUE TITLE
Chevron Arrow

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/TLCMap-support#32]
![image](https://github.com/user-attachments/assets/a806edbe-ee4a-415e-b67a-306100c31017)
This relates to the downwards pointing arrow to the left of the “Enter search” box. The same chevron arrow is used for the information that comes up when you click on a place on the map. It is used to expand and collapse the table of information about the place. But sometimes a downwards arrow means expand and sometimes it means collapse. You might need to collapse a place, close the info, and then open a few other places to replicate the issue. 

By convention the advanced search chevron button at the top of the interface probably belongs after the Search button or immediately before…. where one would expect to see the words “Advanced search…” as a hyperlink. At the moment users confused it for a kind of bullet point symbol that did nothing - just an artefact of the layout rather than something that could be interacted with. Changing it to “Advanced search…” could also resolve the issue of inconsistency of the symbol raised above. Alternatively “More…” to the immediate right of a search button would imply “Advanced Search…”, but use a lot less space!

Under the advanced search there is a “Search Description” checkbox. Suggest changing to “Also search Description field”.

**Comment by BillPascoe** [comment]
Agree with "More..." to be added to the right.
Leave it as 'Search Description' but add tooltip question mark that says "Also search the Description of places".

**Comment by IanMcCrabb** [comment]
This relates to the downwards pointing arrow to the left of the “Enter search” box. The same chevron arrow is used for the information that comes up when you click on a place on the map. It is used to expand and collapse the table of information about the place. But sometimes a downwards arrow means expand and sometimes it means collapse. You might need to collapse a place, close the info, and then open a few other places to replicate the issue.

Ian:  This seems to have been fixed.

By convention the advanced search chevron button at the top of the interface probably belongs after the Search button or immediately before…. where one would expect to see the words “Advanced search…” as a hyperlink. At the moment users confused it for a kind of bullet point symbol that did nothing - just an artefact of the layout rather than something that could be interacted with. Changing it to “Advanced search…” could also resolve the issue of inconsistency of the symbol raised above. Alternatively “More…” to the immediate right of a search button would imply “Advanced Search…”, but use a lot less space!

Ian: Perhaps we can just shift the chevron to the tight of the search box.  

Under the advanced search there is a “Search Description” checkbox. Suggest changing to “Also search Description field”.

Ian: leave is as 'Search Description' but add tooltip question mark that says "Also search the Description of places".

**Comment by IanMcCrabb** [comment]
OK
