### ISSUE TITLE
Map Options

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/TLCMap-support#33]
![image](https://github.com/user-attachments/assets/6377104d-c13b-4264-bd6f-f39493ad1750)

The tooltip on the button in the top right hand corner of the map says “Expand”. This is the button that shows/hides the different map overlay options (“Satelite”, “Streets”, “Topographic” etc). This tooltip could be something like “Map overlay options” - at the moment users don’t know what is being expanded. 

The buttons to draw shapes on the map in the top right hand corner of the map have tooltips like “Draw a Polygon” and “Draw a square” when the user mouses over them. Could be “Search within a polygon” instead. Or “Draw and search within a polygon”. 

The shape buttons and undo/redo buttons are a bit confusing until the advanced search has been expanded. Try drawing a square when the page first loads and you’ll see what I mean - you know to draw the square and click the search button, but a new user doesn’t know this. They just drew the square and then nothing happened! I suggest disabling these buttons (greyed out) until the advanced search is expanded… or if a user clicks on any disabled buttons the advanced search is expanded and the buttons are enabled. Alternatively, hide all the buttons until expanding advanced search.

**Comment by BillPascoe** [comment]
Tooltip to say 'Draw polygon, click search.' Same for circle etc.
Suggestions to make these available only with advanced search aren't easily accomplished as the buttons are built in to ARCGis system, not our custom systems.

**Comment by IanMcCrabb** [comment]
OK
