### ISSUE TITLE
Plus Button

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/TLCMap-support#34]
![image](https://github.com/user-attachments/assets/782836ee-29a5-4561-bc21-4344477fcd04)
This refers to the plus button in the bottom right hand corner that takes a user to sign up or create a new place if they are already logged in. 

The plus symbol is the same as the zoom in button on the map (top left hand corner - zoom in and zoom out). This could cause confusion. It’s possible the symbol selection is limited for the mapping platform, in this case, suggest trying to make it bold to distinguish it more. But you might be able to change the class to one of these symbols instead:

●	esri-icon-map-pin
●	esri-icon-blank-map-pin
●	esri-icon-table
●	esri-icon-add-attachment

See: https://developers.arcgis.com/javascript/latest/esri-icon-font/#css-class-names-and-unicode-values 

The add new place button should have a tooltip in the same way that the shape buttons do. “Contribute to TLCMap…” or similar. 

The plus/add button in the bottom right-hand corner of the map should be the same colour as the "Layers" checkbox option above the map. At the moment it is the same colour as the ANPS checkbox. New users will typically be adding Layers, at least to start with. Would also be good to round the border of the add button in order to match the Layers checkbox background and emphasise they are related.

**Comment by BillPascoe** [comment]
Yes good point. The icon should not be same as zoom. Since it is to add your own dot to the map it should use the same icon as our points on the map - a dot. And perhaps it should indicate 'add one of these dots'. Eg: a dot with a plus sign. (In Google Earth which uses 'pins' it has a pin with a little plus sign to the top right.)

**Comment by MufengNiu** [comment]
Have changed the background colour,  icon changed to  to 'esri-icon-map-pin', the tooltip says 'Contribute to TLCMap'

**Comment by IanMcCrabb** [comment]
OK
