### ISSUE TITLE
Loading Random Places

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/TLCMap-support#35]
The loading of random places on the map should either be once off or additive. Currently the map loads more places as a user pans/zooms, replacing the existing points. Users lost track of the pin they were zooming in on to see what/where exactly it was!

Users were unsure how the randomly chosen places were chosen. Users spent a lot of time asking this question and tried to understand the site by clicking through multiple places to work out what was going on. They were confused further when some of the places were outside of Australia. Perhaps starting with a circle shape drawn on the map could fix some of these issues - “oh, it’s only searching for 100 places within this circle”. Might be technical barriers to this solution though. 

The spinning wheel “Loading doughnut” could have text under it that explains. “Loading more random and interesting places, events, etc…”.

**Comment by BillPascoe** [comment]
Good point. If I clicked a point, and want to go and see it again but have moved, it's probably lost. Not sure how to handle this though. What do would Google do?

**Comment by IanMcCrabb** [comment]
What google does is that as you move the window it pops up the option to 'search this area'.  

We can consider staying with our current behaviour but make it additive by default.  Might need to investigate what the coding changes (and performance issues) would be to keep adding 200/500/ more as one moved the window.  Indeed, we might need to make that behaviour an optional switch.  @MufengNiu I think just some investigation first before we make any changes.

**Comment by MufengNiu** [comment]
If a user initiates a bounding box change, the new bounding box and the old one might overlap. On the backend, we search for a specific number of points within the bounding box, so the new 200/500 points might include many of the same points as the old bounding box. We can filter these duplicates on the frontend to avoid repetition; however, the resulting number of points might not be 200+200 or 500+500.

Performance shouldn’t be an issue since the map can easily handle displaying a few thousand points.

**Comment by MufengNiu** [comment]
Have implemented the additive feature when bounding box change event. 
Currently no limit is set.
If a user initial a new search, or press the reset button, the map will clear all the old points first.

**Comment by IanMcCrabb** [comment]
@MufengNiu I like this.  Lets see what others think tomorrow.

We could consider adding  a check box to the right of where it says 200 places that toggles the additive feature on/off.
We also need to consider the impact of not having a limit.
