### ISSUE TITLE
Access to site

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/TLCMap-support#37]
Can't access the site at the moment form hamburger menu

![image](https://github.com/user-attachments/assets/90fe758f-8d29-445d-bd39-ab14963ffd21)

**Comment by IanMcCrabb** [comment]
Get this as the url http://ec2-13-210-15-31.ap-southeast-2.compute.amazonaws.com/tlcmap/tools/  I seem to recall that we were going to set up a domain name for the documentation site.  Perhaps this is just because we are in testing...

**Comment by MufengNiu** [comment]
@IanMcCrabb , we dont have a domain name for this one yet
