### ISSUE TITLE
Certificate error and redirects

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/TLCMap-support#51]
I have found that https://www.tlcmap.org/ is giving the certificate error.  https://tlcmap.org/ is ok.
If you select to proceed to [www.tlcmap.org](http://www.tlcmap.org/) it doesn't show the map, probably because of things needing either the 's' in https or the URLs are hardcoded as tlcmap.org not [www.tlcmap.org](http://www.tlcmap.org/) etc, etc.
I think we don't need to have everything functioning at [www.tlcmap.org](http://www.tlcmap.org/) as it would at tlcmap.org. 
I think we could simply redirect every request for [www.tlcmap.org](http://www.tlcmap.org/) to the tlcmap.org equivalent.
Ie: 
If they go to https://www.tlcmap.org/layers currently it treats this like a valid URL and tries to return the layers page keeping the URL in the address bar as  https://www.tlcmap.org/layers
Instead it could simply redirect to https://tlcmap.org/layers 
This could be done with apache host config.
This should work, unless Google checks certificate before it reaches our apache response.  If that's the case, I guess we need to figure out how to add [www.tlcmap.org](http://www.tlcmap.org/) to the certificate, or create a new one for it.

**Comment by MufengNiu** [comment]
@yangli0516 @IanMcCrabb  Fixed
