### ISSUE TITLE
Search for a list of placenames broken

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/TLCMap-support#8]
If I upload a .txt file containing a list of placenames one on each line and search, it gives a timeout error.
Eg:
Newcastle
Maitland
Morpeth

Even if it just has 'Newcastle' in it, it times out.

Then any other search gives a time out error. Refresh doesn't correct it but hard refresh does so it's probably because it has retained the uploaded file that it can't process properly.

**Comment by IanMcCrabb** [comment]
@MufengNiu need to check that this is working.  I don't get a timeout but when I loaded a txt file it did  not seem to search for the values in the txt file

**Comment by MufengNiu** [comment]
Fixed

**Comment by IanMcCrabb** [comment]
OK
